version: '3.1'
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'rabbitmq'
        ports:
            - "15672:15672"
            - "5672:5672"
            - "5671:5671"
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        environment:
            RABBITMQ_DEFAULT_PASS: "guest"
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_VHOST: "/"
        networks:
            - auto-assigner
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./mongo:/data/db
        networks:
            - auto-assigner
    back:
        depends_on: 
            - mongo
            - rabbitmq
        container_name: back
        build: 
            context: ./
            dockerfile: Dockerfile
        ports:
            - 8000:8000
            - 9229:9229
        volumes:
            - ./:/api
        environment:
            - ENV=local
        networks:
            - auto-assigner

networks:
  auto-assigner:
    driver: bridge
